(deftheme andear "A custom theme by Andy")
(custom-theme-set-faces
  'andear
  '(default ((t (:foreground "#cccccc" :background "#000000"))))
  '(cursor ((t (:background "#d5dfcd"))))q
  '(linum ((t (:background "#3D3D3D"))))
  '(mode-line ((t (:foreground "#cccccc" :background "#24281f"))))
  '(vertical-border ((t (:foreground "#161322" :background "#161322"))))
  '(region ((t (:background "#24281f"))))
  '(font-lock-builtin-face ((t (:foreground "#2c7baf"))))
  '(font-lock-comment-face ((t (:foreground "#6b6c6a"))))
  '(font-lock-function-name-face ((t (:foreground "#1e86f1"))))
  '(font-lock-keyword-face ((t (:foreground "#3a9b12"))))
  '(font-lock-string-face ((t (:foreground "#a64726"))))
  '(font-lock-type-face ((t (:foreground"#8683f1"))))
  '(font-lock-constant-face ((t (:foreground "#eeeeec"))))
  '(font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
  '(minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'andear)
